using System.Globalization;
using Game.Core.Content;
using Game.Unity.Cards;
using Game.Unity.Definitions;
using UnityEngine;

namespace Game.EditorTools.CardGeneration
{
    /// <summary>
    /// Text of the generated UI Toolkit card template (UXML and USS) and the output folder's README.
    /// Element names come from <see cref="CardTemplate"/>, so the template can't drift from the code that
    /// fills it. Colours in the USS are preview defaults taken from the palette; at runtime
    /// <see cref="CardTemplate.Bind"/> applies the palette directly.
    /// </summary>
    public static class CardTemplateFiles
    {
        public const string UxmlFileName = "CardTemplate.uxml";
        public const string UssFileName = "CardTemplate.uss";
        public const string ReadmeFileName = "README.md";

        private const float IdLabelAlpha = 0.6f;

        public static string Uxml()
        {
            return
                "<ui:UXML xmlns:ui=\"UnityEngine.UIElements\" editor-extension-mode=\"False\">\n" +
                $"    <Style src=\"{UssFileName}\" />\n" +
                $"    <ui:VisualElement name=\"{CardTemplate.RootName}\" class=\"card\">\n" +
                $"        <ui:Label name=\"{CardTemplate.IdLabelName}\" class=\"card__id\" text=\"SetA_Common_01\" />\n" +
                $"        <ui:VisualElement name=\"{CardTemplate.FaceName}\" class=\"card__face\">\n" +
                $"            <ui:Label name=\"{CardTemplate.NameLabelName}\" class=\"card__name\" text=\"Card Name\" />\n" +
                $"            <ui:Label name=\"{CardTemplate.TierLabelName}\" class=\"card__tier\" text=\"Common\" />\n" +
                "        </ui:VisualElement>\n" +
                "    </ui:VisualElement>\n" +
                "</ui:UXML>\n";
        }

        public static string Uss(RarityPaletteDefinition palette)
        {
            string frame = Rgb(palette.ColorOf(RarityTier.Common));
            string face = Rgb(palette.CardFaceColor);
            string text = Rgb(palette.CardTextColor);
            Color idColor = palette.CardTextColor;
            idColor.a = IdLabelAlpha;

            return
                "/* Generated by TCG > Generate Prototype Card Data. Colours are preview defaults from the Rarity\n" +
                "   Palette; CardTemplate.Bind applies the palette at runtime. */\n" +
                ".card {\n" +
                "    width: 250px;\n" +
                "    height: 350px;\n" +
                "    padding: 12px;\n" +
                "    border-width: 8px;\n" +
                "    border-radius: 16px;\n" +
                $"    border-color: {frame};\n" +
                $"    background-color: {face};\n" +
                "}\n" +
                "\n" +
                ".card__id {\n" +
                "    position: absolute;\n" +
                "    top: 8px;\n" +
                "    right: 12px;\n" +
                "    font-size: 11px;\n" +
                $"    color: {Rgba(idColor)};\n" +
                "}\n" +
                "\n" +
                ".card__face {\n" +
                "    flex-grow: 1;\n" +
                "    justify-content: center;\n" +
                "    align-items: center;\n" +
                "}\n" +
                "\n" +
                ".card__name {\n" +
                "    font-size: 26px;\n" +
                "    -unity-font-style: bold;\n" +
                "    -unity-text-align: middle-center;\n" +
                "    white-space: normal;\n" +
                $"    color: {text};\n" +
                "}\n" +
                "\n" +
                ".card__tier {\n" +
                "    margin-top: 10px;\n" +
                "    font-size: 18px;\n" +
                "    -unity-font-style: bold;\n" +
                "    -unity-text-align: middle-center;\n" +
                $"    color: {frame};\n" +
                "}\n";
        }

        public static string Readme()
        {
            return
                "# Generated card data\n" +
                "\n" +
                "Everything in this folder is generated by **TCG > Generate Card Data** from the CSV manifests in " +
                "`Data/Manifests/` (`Sets.csv`, one card file per set, `TierPrices.csv`). Edit the CSVs, never these assets, " +
                "then regenerate.\n" +
                "\n" +
                "- `Cards/<setId>/`: one CardDefinition per manifest row, named by its id (`RC_C_014`).\n" +
                "- `<setId>.asset`: one card set per `Sets.csv` row. Pack configurations point at these.\n" +
                "- `Materials/`: URP Lit materials whose colours come from the Rarity Palette (`Data/Visuals/RarityPalette.asset`).\n" +
                "- `Prefabs/`: `BoosterPack` (pack prop) and `WorldCard` (world-space card, filled by `WorldCardView`).\n" +
                "- `UI/`: `CardTemplate.uxml` and `.uss`, the UI Toolkit card template (filled by `CardTemplate.Bind`).\n" +
                "\n" +
                "The generator upserts by id: new rows create assets, changed rows update them in place (same GUID), and rows " +
                "that disappeared are reported, never deleted. Assets are never deleted and re-created, so scene and pack " +
                "references survive a regeneration; after a run it re-links known references and reports any it couldn't.\n";
        }

        private static string Rgb(Color color)
        {
            Color32 bytes = color;
            return $"rgb({bytes.r}, {bytes.g}, {bytes.b})";
        }

        private static string Rgba(Color color)
        {
            Color32 bytes = color;
            return string.Format(CultureInfo.InvariantCulture, "rgba({0}, {1}, {2}, {3:0.##})", bytes.r, bytes.g, bytes.b, color.a);
        }
    }
}
